### ISSUE TITLE
Too many login attempts

### ISSUE THREAD

**Issue by stevenleeg** [femueller/python-n26#125]
Hi there,

I've been struggling quite a bit with the following error while trying to use this library:

```
ValueError: Unexpected response for initial auth request: {"status":429,"detail":"Too many log-in attempts. Please try again in 30 minutes.","userMessage":{"title":"Oops!","detail":"Too many log-in attempts. Please try again in 30 minutes."},"error":"Oops!","title":"Oops!","message":"Too many log-in attempts. Please try again in 30 minutes."}
```

It seems like this error is happening pretty randomly, not just for too many attempts within a 30 minute window. That is, I can wait for a few days without making any login attempts, try to execute the `n26 balance` command, and then still see this error message come up. It's not 100% of the time though, as it will sometimes randomly let me through with no issues and everything will work for a few minutes before I receive another auth error (will post next time I see it, but i'm currently stuck at this too many attempts error).

I have a feeling I'm doing something incorrectly, but I believe I've followed the instructions properly. For additional context, I have a `n26.yaml` file in the current working directory that looks like this:

```yaml
n26:
    username: "[email address]"
    password: "[password]"
    device_token: "[uuid generated as instructed]"
    login_data_store_path: "~/.config/n26/token_data"
    mfa_type: app
```

Any ideas as to what's going on here? (Also thank you for all the hard work you've put into this library; in the times I've gotten through this auth issue everything works great!)
